vich_uploader:
    db_driver: orm

    mappings:
        gites:
            uri_prefix: /images/gites
            upload_destination: '%kernel.project_dir%/public/images/gites'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
